from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
import re
from backend.llm.service import ChatCompletionService
from backend.repointel.service import RepositoryIntelligenceEngine
from backend.runtime.file_editor import FileEditor
from backend.runtime.gitops import GitOperations
from backend.runtime.patches import PatchRisk, PatchTarget, StructuredPatch
from backend.runtime.validation import PatchValidator
from backend.runtime.worktrees import WorktreeInfo, WorktreeManager

logger = logging.getLogger(__name__)

_MAX_RETRIES = 3


@dataclass(slots=True)
class CodingTask:
    task_id: str
    prompt: str
    agent_name: str = "coder-agent"
    max_retries: int = _MAX_RETRIES


@dataclass(slots=True)
class AgentResult:
    patch: StructuredPatch
    attempts: int
    succeeded: bool


class AutonomousCoderAgent:
    """
    Autonomous coding agent.

    Responsibilities:
    - retrieve repo context
    - query LLM
    - modify isolated worktree (multi-file)
    - stage + collect git diff
    - validate patch with retry loop
    """

    def __init__(
        self,
        repo_root: str,
        llm_service: ChatCompletionService,
        repo_intel: RepositoryIntelligenceEngine,
    ) -> None:
        self.repo_root = repo_root
        self.llm_service = llm_service
        self.repo_intel = repo_intel
        self.worktrees = WorktreeManager(repo_root=repo_root)
        self.validator = PatchValidator()

    async def execute(self, task: CodingTask) -> AgentResult:
        worktree = await self.worktrees.create_worktree(task.agent_name)
        try:
            return await self._execute_in_worktree(task=task, worktree=worktree)
        finally:
            await self.worktrees.remove_worktree(worktree)

    async def _execute_in_worktree(
        self,
        task: CodingTask,
        worktree: WorktreeInfo,
    ) -> AgentResult:
        repo_context = await self.repo_intel.build_context(task.prompt)
        editor = FileEditor(repo_root=str(worktree.path))
        gitops = GitOperations(repo_path=str(worktree.path))

        validation_errors: list[str] = []
        last_patch: StructuredPatch | None = None

        for attempt in range(1, task.max_retries + 1):
            logger.info(
                "Agent %s attempt %d/%d for task %s",
                task.agent_name, attempt, task.max_retries, task.task_id,
            )

            prompt = self._build_prompt(
                task_prompt=task.prompt,
                repo_context=repo_context,
                previous_errors=validation_errors,
            )

            response = await self.llm_service.generate_text(
                prompt=prompt,
                temperature=0.1,
            )

            try:
                parsed = self._parse_response(
                    response
                )

            except Exception as exc:

                validation_errors = [
                    str(exc)
                ]

                logger.warning(
                    "Task %s attempt %d "
                    "failed parsing: %s",
                    task.task_id,
                    attempt,
                    validation_errors,
                )

                continue

            # Multi-file write
            impacted: list[PatchTarget] = []
            for file_path, content in parsed["files"].items():
                editor.write_file(relative_path=file_path, content=content)
                impacted.append(PatchTarget(path=file_path))

            # Stage everything so diff --cached captures new files too
            await gitops.stage_all()
            diff = await gitops.get_staged_diff()

            last_patch = StructuredPatch(
                title=task.prompt,
                summary=parsed.get("summary", task.prompt),
                reasoning=parsed.get("reasoning", "Generated by autonomous coder agent."),
                unified_diff=diff,
                impacted_files=impacted,
                risk=PatchRisk(parsed.get("risk", PatchRisk.MEDIUM)),
                metadata={
                    "agent_name": task.agent_name,
                    "workspace_id": worktree.workspace_id,
                    "branch_name": worktree.branch_name,
                    "attempt": attempt,
                },
            )

            validated = self.validator.validate(last_patch)

            if validated.is_valid():
                logger.info("Task %s succeeded on attempt %d", task.task_id, attempt)
                return AgentResult(patch=validated, attempts=attempt, succeeded=True)

            validation_errors = validated.validation_errors
            last_patch = validated
            logger.warning(
                "Task %s attempt %d failed validation: %s",
                task.task_id, attempt, validation_errors,
            )

        # All retries exhausted — return last patch with errors intact
        logger.error("Task %s failed after %d attempts.", task.task_id, task.max_retries)
        return AgentResult(
            patch=last_patch,  # type: ignore[arg-type]
            attempts=task.max_retries,
            succeeded=False,
        )

    def _build_prompt(
        self,
        task_prompt: str,
        repo_context: str,
        previous_errors: list[str],
    ) -> str:
        error_section = ""
        if previous_errors:
            joined = "\n".join(f"- {e}" for e in previous_errors)
            error_section = f"\nPREVIOUS ATTEMPT FAILED WITH:\n{joined}\nFix these.\n"

        return f"""You are an autonomous coding agent.

TASK:
{task_prompt}

REPOSITORY CONTEXT:
{repo_context}
{error_section}
You MUST respond with valid JSON.

Format:

{{
  "summary": "one line description of what you did",
  "reasoning": "why you made these changes",
  "risk": "low|medium|high|unknown",
  "files": {{
    "relative/path/file.py": "FULL FILE CONTENT",
    "another/file.py": "FULL FILE CONTENT"
  }}
}}

Rules:
- Return ONLY valid JSON
- No markdown, no backticks
- Full file rewrites only
- Multiple files allowed
"""

    def _parse_response(self, response: str) -> dict:
        # Strip markdown fences if model misbehaves
        cleaned = response.strip()

        cleaned = re.sub(
            r"^```(?:json)?",
            "",
            cleaned,
            flags=re.IGNORECASE,
        ).strip()

        cleaned = re.sub(
            r"```$",
            "",
            cleaned,
        ).strip()

        try:
            parsed = json.loads(cleaned)
        except Exception as exc:
            raise RuntimeError("Failed to parse LLM JSON response.") from exc

        if "files" not in parsed or not isinstance(parsed["files"], dict):
            raise RuntimeError("Missing or invalid 'files' in LLM response.")

        if not parsed["files"]:
            raise RuntimeError("LLM returned empty files dict.")

        return parsed